// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv functions/types/cloudflare-env.d.ts`

interface CloudflareEnv {
  VAULT_BLOCK_KV: KVNamespace;
  VITE_MAX_VAULTS: 5;
  NOTION_API_VERSION: "2022-06-28";
  MAX_PAGES: number;
  NOTION_CLIENT_ID: string;
  NOTION_CLIENT_SECRET: string;
  REDIRECT_URL: string;
  ACCESS_TOKEN_SECRET: string;
  REFRESH_TOKEN_SECRET: string;
  DB: D1Database;
}

// Just a note wrangler keeps generating MAX_PAGES as string instead of number
